// <auto-generated />
using System;
using DataStorage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataStorage.Migrations
{
    [DbContext(typeof(ImagesLibraryContext))]
    [Migration("20211116103514_FirstVersion")]
    partial class FirstVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DataStorage.ImageInfo", b =>
                {
                    b.Property<int>("ImageInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageHash")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImageInfoDetailsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT");

                    b.HasKey("ImageInfoId");

                    b.HasIndex("ImageInfoDetailsId");

                    b.ToTable("ImagesInfo");
                });

            modelBuilder.Entity("DataStorage.ImageInfoDetails", b =>
                {
                    b.Property<int>("ImageInfoDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.HasKey("ImageInfoDetailsId");

                    b.ToTable("ImagesInfoDetails");
                });

            modelBuilder.Entity("DataStorage.RecognizedObject", b =>
                {
                    b.Property<int>("ObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int?>("ImageInfoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ObjectId");

                    b.HasIndex("ImageInfoId");

                    b.ToTable("RecognizedObjects");
                });

            modelBuilder.Entity("DataStorage.ImageInfo", b =>
                {
                    b.HasOne("DataStorage.ImageInfoDetails", "ImageInfoDetails")
                        .WithMany()
                        .HasForeignKey("ImageInfoDetailsId");

                    b.Navigation("ImageInfoDetails");
                });

            modelBuilder.Entity("DataStorage.RecognizedObject", b =>
                {
                    b.HasOne("DataStorage.ImageInfo", null)
                        .WithMany("RecognizedObjects")
                        .HasForeignKey("ImageInfoId");
                });

            modelBuilder.Entity("DataStorage.ImageInfo", b =>
                {
                    b.Navigation("RecognizedObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
